// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmKhsnMYoGQceDmtMlQZirOgKrDKqbB1s',
    appId: '1:296547997379:web:fbce667be701df300ab476',
    messagingSenderId: '296547997379',
    projectId: 'safepath-ai-sujal',
    authDomain: 'safepath-ai-sujal.firebaseapp.com',
    storageBucket: 'safepath-ai-sujal.firebasestorage.app',
    measurementId: 'G-RG5Q064QBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxr5i6sI8alonyuemvbJWR7gBIMZPNkTI',
    appId: '1:296547997379:android:1ecd43f4f20fe5890ab476',
    messagingSenderId: '296547997379',
    projectId: 'safepath-ai-sujal',
    storageBucket: 'safepath-ai-sujal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv1i6RX3bp-0iXaEwb-9oCVe3oAfzw9rc',
    appId: '1:296547997379:ios:9aa89d4204c4f1000ab476',
    messagingSenderId: '296547997379',
    projectId: 'safepath-ai-sujal',
    storageBucket: 'safepath-ai-sujal.firebasestorage.app',
    iosBundleId: 'com.example.safePathAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv1i6RX3bp-0iXaEwb-9oCVe3oAfzw9rc',
    appId: '1:296547997379:ios:9aa89d4204c4f1000ab476',
    messagingSenderId: '296547997379',
    projectId: 'safepath-ai-sujal',
    storageBucket: 'safepath-ai-sujal.firebasestorage.app',
    iosBundleId: 'com.example.safePathAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmKhsnMYoGQceDmtMlQZirOgKrDKqbB1s',
    appId: '1:296547997379:web:43bc347ea0ac94af0ab476',
    messagingSenderId: '296547997379',
    projectId: 'safepath-ai-sujal',
    authDomain: 'safepath-ai-sujal.firebaseapp.com',
    storageBucket: 'safepath-ai-sujal.firebasestorage.app',
    measurementId: 'G-4QTLFCQBD1',
  );
}
